* Operators on Complex Vector Spaces

Our assumptions for this chapter are the following: 

- $F$ denotes $R$ or $C$
- $V$ denotes a finite-dimensional nonzero vector space over $F$

** Learning Objectives for this Chapter 

- Generalized Eigenvectors and Generalized Eigenspaces
- Characteristic Polynomial and the Cayley-Hamilton Theorem
- Decomposition of an Operator
- Minimal Form
- Jordan Form 

** Generalized Eigenvectors and Nilpotent Operators 

We begin this chapter with a study of null spaces of powers of an operator 

*** Theorem | Sequence of Increasing Null Spaces 

Suppose $T \in \mathcal{L}(V)$. Then $\{0\} = \mathrm{null} T^0 \subset \mathrm{null} T^1 \subset ... \subset \mathrm{null} T^k \subset \mathrm{null} T^{k + 1} \subset$
  
*** Theorem | Equality in the Sequence of Null Spaces 

Suppose $T \in \mathcal{L}(V)$. Suppose $m$ is a non-negative integer such that $\mathrm{null} T^m = \mathrm{null}T^{m + 1}$. 
Then $\mathrm{null} T^m = \mathrm{null} T^{m + 1} = \mathrm{null} T^{m + 2} = \mathrm{null} T^{m + 3} =$

*** Theorem | Null Spaces Stop Growing 

Suppose $T \in \mathcal{L}(V)$. Let $n = \mathrm{dim}(V)$. Then $\mathrm{null}T^n = \mathrm{null}T^{n + 1} = \mathrm{null}T^{n + 2} =$

The equality in the sequence of null spaces theorem raises the question of whether there exists a non-negative integer $m$ such that null $T^m$ = null $T^{m + 1}$. The proposition above shows that this equality holds at least when $m$ equals the dimension of the vector space on which $T$ operates. 

*** Theorem | $V$ is the direct sum of null $T^{\mathrm{dim}V}$ and range $T^{\mathrm{dim}V}$

Suppose $T \in \mathcal{L}(V)$. Let $n = \mathrm{dim}V$. Then $V = \mathrm{null}T^n \oplus \mathrm{range}T^n$

*** Definition | Generalized Eigenvector 

Suppose $T \in \mathcal{L}(V)$ and $\lambda$ is an eigenvalue of $T$. A vector $v \in V$ is called a generalized eigenvector of $T$ corresponding to $\lambda$ if $v \neq 0$ and $(T - \lambda I)^j v = 0$ for some positive integer $j$. 

*** Definition | Generalized Eigenspace $G(\lambda, T)$

Suppose $T \in \mathcal{L}(V)$ and $\lambda \in F$. The generalized eigenspace of $T$ corresponding to $\lambda$, denoted $G(\lambda, T)$ is defined to be the set of all generalized eigenvectors of $T$ corresponding to $\lambda$, along with the 0 vector. 

*** Theorem | Description of Generalized Eigenspaces 

Suppose $T \in \mathcal{L}(V)$ and $\lambda \in F$. Then $G(\lambda, T) = \mathrm{null}(T - \lambda I)^{\mathrm{dim}V}$. 

*** Theorem | Linearly Independent Generalized Eigenvectors

Let $T \in \mathcal{L}(V)$. Suppose $\lambda_1, ..., \lambda_m$ are distinct eigenvalues of $T$ and $v_1, ..., v_m$ are corresponding generalized eigenvectors. Then $v_1, ..., v_m$ is linearly independent. 

*** Definition | Nilpotent 

An operator is called nilpotent if some power of it equals 0

*** Theorem | Nilpotent Operator Raised to Dimension of Domain is 0 

Suppose $N \in \mathcal{L}(V)$ is nilpotent. Then $N^{\mathrm{dim}(V)} = 0$

*** Theorem | Matrix of a Nilpotent Operator 

Suppose $N$ is a nilpotent operator on $V$. Then there is a basis of $V$ with respect to which the matrix of $N$ has the form 

$\begin{pmatrix} 0 \cdots * \\ \hspace \ddots \hspace \\ 0 \hspace 0 \end{pmatrix}$

here all entries on and below the diagonal are 0s.

** Decomposition of an Operator 

In this section we will see that every operator on a finite-dimensional complex vector space has enough generalized eigenvectors to provide a decomposition. 

*** Theorem | The null space and range of $p(T)$ are invariant under $T$

Suppose $T \in \mathcal{L}(V)$ and $p \in \mathcal{P}(F)$. Then null $p(T)$ and range $p(T)$ are invariant under $T$

This next result shows that every operator on a complex vector space can be thought of as composed of pieces, each of which is a nilpotent operator plus a scalar multiple of the identity. 

*** Theorem | Description of Operators on Complex Vector Spaces 

Suppose $V$ is a complex vector space and $T \in \mathcal{L}(V)$. Let $\lambda_1, ..., \lambda_m$ be the distinct eigenvalues of $T$. Then 

- $V = G(\lambda_1, T) \oplus ... \oplus G(\lambda_m, T)$
- each $G(\lambda_j, T)$ is invariant under $T$
- each $(T - \lambda_j I)_{|G(\lambda_j, T)}$ is nilpotent

*** Theorem | A basis of generalized eigenvectors 

Suppose $V$ is a complex vector space and $T \in \mathcal{L}(V)$. Then there is a basis of $V$ consisting of generalized eigenvectors of $T$

*** Definition | Multiplicity 

Suppose $T \in \mathcal{L}(V)$. The multiplicity of an eigenvalue $\lambda$ of $T$ is defined to be the dimension of the corresponding generalized eigenspace $G(\lambda, T)$. In other words, the multiplicity of an eigenvalue $\lambda$ of $T$ equals dim null$(T - \lambda I)^{\mathrm{dim}V}$

*** Theorem | Sum of the Multiplicities equals dim $V$

Suppose $V$ is a complex vector space and $T \in \mathcal{L}(V)$. Then the sum of the multiplicities of all the eigenvalues of $T$ equals dim $V$

*** Definition | Block Diagonal Matrix 

A block diagonal matrix is a square matrix of the form

$\begin{pmatrix} A_1 & & 0 \\ & \ddots & \\ 0  & & A_m \end{pmatrix}$ 

 where $A_1, ..., A_m$ are square matrices lying along the diagonal and all other entries of the matrix equal 0.

*** Theorem | Block Diagonal Matrix with Upper-Triangular Blocks 

Suppose $V$ is a complex vector space and $T \in \mathcal{L}(V)$. Let $\lambda_1, ..., \lambda_m$ be the distinct eigenvalues of $T$, with multiplicities $d_1, ..., d_m$. Then there is a basis of $V$ with respect to which $T$ has a block diagonal matrix of the form: 

$\begin{pmatrix} A_1 & & 0 \\ & \ddots & \\ 0  & & A_m \end{pmatrix}$

where each $A_j$ is a $d_j$ by $d_j$ upper triangular matrix of the form $A_j = \begin{pmatrix} \lambda_j & & 0 \\ & \ddots & \\ 0  & & \lambda_j \end{pmatrix}$

*** Theorem | Identity plus nilpotent has a square root 

Suppose $N \in \mathcal{L}(V)$ is nilpotent. Then $I + N$ has a square root. 

*** Theorem | Over $C$, invertible operators have square roots 

Suppose $V$ is a complex vector space and $T \in \mathcal{L}(V)$ is invertible. Then $T$ has a square root. 


