* Operators on Complex Vector Spaces

Our assumptions for this chapter are the following: 

- $F$ denotes $R$ or $C$
- $V$ denotes a finite-dimensional nonzero vector space over $F$

** Learning Objectives for this Chapter 

- Generalized Eigenvectors and Generalized Eigenspaces
- Characteristic Polynomial and the Cayley-Hamilton Theorem
- Decomposition of an Operator
- Minimal Form
- Jordan Form 

** Generalized Eigenvectors and Nilpotent Operators 

We begin this chapter with a study of null spaces of powers of an operator 

*** Theorem | Sequence of Increasing Null Spaces 

Suppose $T \in \mathcal{L}(V)$. Then $\{0\} = \mathrm{null} T^0 \subset \mathrm{null} T^1 \subset ... \subset \mathrm{null} T^k \subset \mathrm{null} T^{k + 1} \subset$
  
*** Theorem | Equality in the Sequence of Null Spaces 

Suppose $T \in \mathcal{L}(V)$. Suppose $m$ is a non-negative integer such that $\mathrm{null} T^m = \mathrm{null}T^{m + 1}$. 
Then $\mathrm{null} T^m = \mathrm{null} T^{m + 1} = \mathrm{null} T^{m + 2} = \mathrm{null} T^{m + 3} =$

*** Theorem | Null Spaces Stop Growing 

Suppose $T \in \mathcal{L}(V)$. Let $n = \mathrm{dim}(V)$. Then $\mathrm{null}T^n = \mathrm{null}T^{n + 1} = \mathrm{null}T^{n + 2} =$

The equality in the sequence of null spaces theorem raises the question of whether there exists a non-negative integer $m$ such that null $T^m$ = null $T^{m + 1}$. The proposition above shows that this equality holds at least when $m$ equals the dimension of the vector space on which $T$ operates. 

*** Theorem | $V$ is the direct sum of null $T^{\mathrm{dim}V}$ and range $T^{\mathrm{dim}V}$

Suppose $T \in \mathcal{L}(V)$. Let $n = \mathrm{dim}V$. Then $V = \mathrm{null}T^n \oplus \mathrm{range}T^n$

*** Definition | Generalized Eigenvector 

Suppose $T \in \mathcal{L}(V)$ and $\lambda$ is an eigenvalue of $T$. A vector $v \in V$ is called a generalized eigenvector of $T$ corresponding to $\lambda$ if $v \neq 0$ and $(T - \lambda I)^j v = 0$ for some positive integer $j$. 

*** Definition | Generalized Eigenspace $G(\lambda, T)$

Suppose $T \in \mathcal{L}(V)$ and $\lambda \in F$. The generalized eigenspace of $T$ corresponding to $\lambda$, denoted $G(\lambda, T)$ is defined to be the set of all generalized eigenvectors of $T$ corresponding to $\lambda$, along with the 0 vector. 

*** Theorem | Description of Generalized Eigenspaces 

Suppose $T \in \mathcal{L}(V)$ and $\lambda \in F$. Then $G(\lambda, T) = \mathrm{null}(T - \lambda I)^{\mathrm{dim}V}$. 

*** Theorem | Linearly Independent Generalized Eigenvectors

Let $T \in \mathcal{L}(V)$. Suppose $\lambda_1, ..., \lambda_m$ are distinct eigenvalues of $T$ and $v_1, ..., v_m$ are corresponding generalized eigenvectors. Then $v_1, ..., v_m$ is linearly independent. 

*** Definition | Nilpotent 

An operator is called nilpotent if some power of it equals 0

*** Theorem | Nilpotent Operator Raised to Dimension of Domain is 0 

Suppose $N \in \mathcal{L}(V)$ is nilpotent. Then $N^{\mathrm{dim}(V)} = 0$

*** Theorem | Matrix of a Nilpotent Operator 

Suppose $N$ is a nilpotent operator on $V$. Then there is a basis of $V$ with respect to which the matrix of $N$ has the form 

$\begin{pmatrix} 0 \cdots * \\ \hspace \ddots \hspace \\ 0 \hspace 0 \end{pmatrix}$

here all entries on and below the diagonal are 0s.

** Decomposition of an Operator 


