* Finite-Dimensional Vector Spaces

Learning Objectives for this chapter: 
- span
- linear independence
- bases
- dimension 

** 2.A | Span and Linear Independence

*** Definition | Linear Combination 

A linear combination of a list $v_1, ..., v_m$ of vectors in $V$ is a vector of the form $a_1v_1 + ... + a_mv_m$, where $a_1, ..., a_m \in F$. 

*** Definition | Span

The set of all linear combinations of a list of vectors $v_1, ..., v_m$ in $V$ is called the span of $v_1, ..., v_m$, denoted span$(v_1, ..., v_m)$. In other words, span$(v_1, ..., v_m) = \{a_1v_1 + ... + a_mv_m : a_1, ..., a_m \in F\}$.

The span of the empty list is defined to be $\{0\}$.

*** Theorem | Span is the smallest containing subspace 

The span of a list of vectors in $V$ is the smallest subspace of $V$ containing all the vectors in the list. 

*** Definition | Spans 

If span$(v_1, ..., v_m)$ equals $V$, we say that $v_1, ..., v_m$ spans $V$

*** Definition | Finite-Dimensional Vector Space 

A vector space is called finite-dimensional if some list of vectors in it spans the space 

*** Definition | Polynomial $\mathcal{P}(F)$

- A function $p: F \to F$ is called a polynomial with coefficients in $F$ if there exist $a_0, ..., a_m \in F$ such that $p(z) = a_0 + a_1 z + a_2 z^2 + ... + a_m z^m$ for all $z \in F$
- $\mathcal{P}(F)$ is the set of all polynomials with coefficients in $F$ 

The coefficients of a polynomial are uniquely determined by the polynomial. 

*** Definition | Degree of a Polynomial, deg $p$

- A polynomial $p \in \mathcal{P}(F)$ is said to have degree $m$ if there exist scalars $a_0, a_1, ..., a_m \in F$ with $a_m \neq 0$ such that $p(z) = a_0 + a_1z + ... + a_mz^m$ for all $z \in F$. If $p$ has degree $m$, we write deg $p = m$.
- The polynomial that is identically 0 is said to have degree $- \infty$ 

*** Definition | $\mathcal{P}_m(F)$ 

For $m$, a nonnegative integer $\mathcal{P}_m(F)$ denotes the set of all polynomials with coefficients in $F$ with degree at most $m$

*** Definition | infinite-dimensional vector space 

A vector space is called infinite-dimensional if it is not finite-dimensional 

*** Definition | Linearly Independent 

- A list $v_1, ..., v_m$ of vectors in $V$ is called linearly independent if the only choice of $a_1, ..., a_m \in F$ that makes $a_1v_1 + ... + a_mv_m$ equal 0 is $a_1 = ... = a_m = 0$.
- The empty list () is also declared to be linearly independent

The reasoning above shows that $v_1, ..., v_m$ is linearly independent iff each vector in span $(v_1, ..., v_m)$ has only one representation as a linear combination of $v_1, ..., v_m$. 

*** Definition | Linearly Dependent 

- A list of vectors $V$ is called linearly dependent if it is not linearly independent
- In other words, a list $v_1, ..., v_m$ of vectors in $V$ is linearly dependent if there exist $a_1, ..., a_m \in F$, not all 0, such that $a_1v_1 + ... + a_mv_m = 0$. 

*** Lemma | Linear Dependence Lemma 

Suppose $v_1, ..., v_m$ is a linearly dependent list in $V$. Then there exists $j \in \{1, 2, ..., m\}$ such that the following hold: 
- $v_j \in \mathrm{span}(v_1, ..., v_{j - 1})$
- if the jth term is removed from $v_1, ..., v_m$, the span of the remaining list equals $\mathrm{span}(v_1, ..., v_m)$. 

*** Theorem | Length of Linearly Independent List $\leq$ Length of Spanning List

In a finite-dimensional vector space, the length of every linearly independent list of vectors is less than or equal to the length of every spanning list of vectors. 

*** Theorem | Finite-Dimensional Subspaces 

Every subspace of a finite-dimensional vector space is finite-dimensional

** 2.B | Bases 

*** Definition | Basis 

A basis of $V$ is a list of vectors in $V$ that is linearly independent and spans $V$

*** Theorem | Criterion for Basis 

A list $v_1, ..., v_n$ of vectors in $V$ is a basis iff every $v \in V$ can be written uniquely in the form $v = a_1v_1 + ... + a_nv_n$ where $a_1, ..., a_n \in F$

*** Theorem | Spanning List Contains a Basis 

Every spanning list in a vector space can be reduced to the basis of the vector space.

This result says that given any spanning list, some (possibly none) of the vectors in it can be discarded so that the remaining list is linearly independent and still spans the vector space. 

*** Corollary | Basis of Finite Dimensional Vector Space

Every finite dimensional vector space has a basis 

By definition, every FDVS has a spanning list. The previous result tells us that it can be reduced to a basis 

*** Theorem | Linearly Independent List Extends to a Basis 

Every linearly independent list of vectors in a finite-dimensional vector space can be extended to a basis of the vector space 

*** Theorem | Every Subspace of $V$ is part of a direct sum equal to $V$

Suppose $V$ is finite-dimensional and $U$ is a subspace of $V$. Then there is a subspace $W$ of $V$ such that $V = U \oplus W$. 

This shows that every subspace of a finite dimensional vector space can be paired with another subspace to form a direct sum of the whole space. 


** 2.C | Dimension 

*** Theorem | Basis Length does not depend on basis 

Any two bases of a finite-dimensional vector space have the same length

*** Definition | Dimension, dim $V$

- The dimension of a finite-dimensional vector space is the length of any basis of the vector space
- The dimension of $V$ (if $V$ is finite-dimensional) is denoted by dim $V$

*** Theorem | Dimension of a Subspace 

If $V$ is finite-dimensional and $U$ is a subspace of $V$, then dim $U \leq$ dim $V$

*** Theorem | Linearly Independent List of the Right Length is a Basis 

Suppose $V$ is finite-dimensional. Then every linearly independent list of vectors in $V$ with length dim $V$ is a basis of $V$.

*** Theorem | Spanning list of the right length is a basis 

Suppose $V$ is finite-dimensional. Then every spanning list of vectors in $V$ with length dim $V$ is a basis of $V$. 

*** Theorem | Dimension of a Sum 

If $U_1$ and $U_2$ are subspaces of a finite-dimensional vector space, then dim$(U_1 + U_2)$ = dim $U_1$ + dim $U_2$ - dim $(U_1 \cap U_2)$. 
