* Operators on Inner Product Spaces 

In this chapter, $V$ and $W$ denote finite-dimensional inner product spaces over $F$

** Learning Objectives for this Chapter 

- Adjoint
- Spectral Theorem
- Positive Operators
- Isometries
- Polar Decomposition
- Singular Value Decomposition

** Self-Adjoint and Normal Operators 
*** Definition | Adjoint $T^*$
    
Suppose $T \in \mathcal{L}(V, W)$. The adjoint of $T$ is the function $T^* : W \to V$ such that $\langle Tv, w \rangle = \langle v, T^* w \rangle$ for every $v \in V$ and every $w \in W$. 

*** Theorem | The adjoint is a linear map 

If $T \in \mathcal{L}(V, W)$, then $T^* \in \mathcal{L}(W, V)$

*** Theorem | Properties of the Adjoint 

- $(S + T)^* = S^* + T^*$ for all $S, T \in \mathcal{L}(V, W)$
- $(\lambda T)^* = \bar{\lambda}T^*$ for all $\lambda \in F$ and $T \in \mathcal{L}(V, W)$
- $(T^*)^* = T$ for all $T \in \mathcal{L}(V, W)$
- $I^* = I$, where $I$ is the identity operator on $V$
- $(ST)^* = T^* S^*$ for all $T \in \mathcal{L}(V, W)$ and $S \in \mathcal{L}(W, U)$ where $U$ is an inner product space over $F$ 

*** Theorem | Null Space and Range of $T^*$

Suppose $T \in \mathcal{L}(V, W)$. Then 
- null $T^*$ = $(\mathrm{range} T)^{\perp}$
- range $T^*$ = $(\mathrm{null}T)^{\perp}$
- null $T$ = $(\mathrm{range} T^*)^{\perp}$
- range $T$ = $(\mathrm{null} T^*)^{\perp}$ 

*** Definition | Conjugate Transpose 

The conjugate transpose of an m-by-n matrix is the n-by-m matrix obtained by interchanging the rows and columns and then taking the complex conjugate of each entry

*** Theorem | The matrix of $T^*$ 

Let $T \in \mathcal{L}(V, W)$. Suppose $e_1, ..., e_n$ is an orthonormal basis of $V$ and $f_1, ..., f_m$ is an orthonormal basis of $W$. Then 

$\mathcal{M}(T^*, (f_1, ..., f_m), (e_1, ..., e_n))$

is the conjugate transpose of 

$\mathcal{M}(T, (e_1, ..., e_n), (f_1, ..., f_m))$

*** Definition | self-adjoint 

An operator $T \in \mathcal{L}(V)$ is called self-adjoint if $T = T^*$. In other words, $T \in \mathcal{L}(V)$ is self-adjoint iff $\langle Tv, w \rangle = \langle w, Tv \rangle$ for all $v, w \in V$

A good analogy to keep in mind (especially when $F = C$) is that the adjoint on $\mathcal{L}(V)$ plays a role similar to complex conjugation on $C$. A complex number $z$ is real iff $z = \bar{z}$; thus a self-adjoint operator ($T = T^*$) is analogous to a real number.  

*** Theorem | Eigenvalues of Self-Adjoint Operators are Real 

Every eigenvalue of a self-adjoint operator is real 

*** Theorem | Over $C$, $Tv$ is orthogonal to $v$ for all $v$ only for the $0$ operator 

Suppose $V$ is a complex inner product space and $T \in \mathcal{L}(V)$. Suppose $\langle Tv, v \rangle = 0$ for all $v \in V$. Then $T = 0$. 

*** Theorem | Over $C$, $\langle Tv, v \rangle$ is real for all $v$ only for self-adjoint operators  

Suppose $V$ is a complex inner product space and $T \in \mathcal{L}(V)$. Then $T$ is self-adjoint iff $\langle Tv, v \rangle \in R$ for every $v \in V$. 

*** Theorem | If $T = T^*$ and $\langle Tv, v \rangle = 0$ for all $v$, then $T = 0$

*** Definition | normal 

- An operator on an inner product space is called normal if it commutes with its adjoint
- In other words, $T \in \mathcal{L}(V)$ is normal if $T T^* = T^* T$ 

*** Theorem | $T$ is normal iff $\lVert Tv \rVert = \lVert T^*v \rVert$ for all $v$

 An operator $T \in \mathcal{L}(V)$ is normal iff $\lVert Tv \rVert = \lVert T^*v \rVert$ for all $v \in V$

*** Theorem | For $T$ normal, $T$ and $T^*$ have the same eigenvectors

 Suppose $T \in \mathcal{L}(V)$ is normal and $v \in V$ is an eigenvector of $T$ with eigenvalue $\lambda$. Then $v$ is also an eigenvector of $T^*$ with eigenvalue $\bar{\lambda}$

*** Theorem | Orthogonal eigenvectors for normal operators 

 Suppose $T \in \mathcal{L}(V)$ is normal. Then eigenvectors of $T$ corresponding to distinct eigenvalues are orthogonal. 

** The Spectral Theorem 

The Spectral Theorem characterizes the operators as the normal operators when $F = C$ and as the self-adjoint operators when $F = R$. 
We will be breaking the spectral theorem into the complex and real spectral theorems.

The key part of the Complex Spectral Theorem states that if $F = C$ and $T \in \mathcal{L}(V)$ is normal, then $T$ has a diagonal matrix with respect to some orthonormal basis of $V$. 

*** Theorem | Complex Spectral Theorem 

Suppose $F = C$ and $T \in \mathcal{L}(V)$. Then the following are equivalent: 
- $T$ is normal
- $V$ has an orthonormal basis consisting of eigenvectors of $T$
- $T$ has a diagonal matrix with respect to some orthonormal basis of $V$

*** Theorem | Invertible Quadratic Expressions 

Suppose $T \in \mathcal{L}(V)$ is self-adjoint and $b, c \in R$ are such that $b^2 < 4c$. Then $T^2 + bT + cI$ is invertible. 

*** Theorem | Self-adjoint Operators have Eigenvalues 

Suppose $V \neq \{0\}$ and $T \in \mathcal{L}(V)$ is a self-adjoint operator. Then $T$ has an eigenvalue 

The next result shows that if $U$ is a subspace of $V$ that is invariant under a self-adjoint operator $T$, then $U^{\perp}$ is also invariant under $T$. 

*** Self-adjoint Operators and Invariant Subspaces

Suppose $T \in \mathcal{L}(V)$ is self-adjoint and $U$ is a subspace of $V$ that is invariant under $T$. Then 
- $U^{\perp}$ is invariant under $T$
- $T_{|U} \in \mathcal{L}(U)$ is self-adjoint
- $T_{|U^{\perp}} \in \mathcal{L}(U^{\perp})$ is self-adjoint 

*** Theorem | Real Spectral Theorem 

Suppose $F = R$ and $T \in \mathcal{L}(V)$. Then the following are equivalent: 

- $T$ is self-adjoint
- $V$ has an orthonormal basis consisting of eigenvectors of $T$
- $T$ has a diagonal matrix with respect to some orthonormal basis of $V$

If $F = C$, the complex spectral theorem gives a complete description of the normal operators on $V$. A complete description of the self-adjoint operators on $V$ then follows, as they are the normal operators on $V$ whose eigenvalues are all real. 

If $F = R$, then the real spectral theorem gives a complete description of the self-adjoint operators on $V$. 

** Positive Operators and Isometries

*** Definition | Positive Operator 

An operator $T \in \mathcal{L}(V)$ is called positive if $T$ is self-adjoint and $\langle Tv, v \rangle \geq 0$ for all $v \in V$

If $V$ is a complex vector space, then the requirement that $T$ is self-adjoint can be dropped from the definition above. 

Some mathematicians prefer the term positive semidefinite operator instead of positive operator. 

*** Definition | Square Root 

An operator $R$ is called a square root of an operator $T$ if $R^2 = T$

*** Theorem | Characterization of Positive Operators 

Let $T \in \mathcal{L}(V)$. Then the following are equivalent: 

- $T$ is positive
- $T$ is self-adjoint and all the eigenvalues of $T$ are non-negative
- $T$ has a positive square root
- $T$ has a self-adjoint square root
- there exists an operator $R \in \mathcal{L}(V)$ such that $T = R^* R$

*** Theorem | Each positive operator has only one positive square root 

Every positive operator on $V$ has a unique positive square root 


*** Definition | Isometry 

An operator $S \in \mathcal{L}(V)$ is called an isometry if $\lVert Sv \rVert = \lVert v \rVert$ for all $v \in V$. In other words, an operator is an isometry if it preserves norms. 

An isometry on a real inner product space is often called an orthogonal operator. An isometry on a complex inner product space is often called a unitary operator. 

*** Theorem | Characterization of Isometries 

Suppose $S \in \mathcal{L}(V)$. Then the following are equivalent:

- $S$ is an isometry
- $\langle Su, Sv \rangle = \langle u, v \rangle$ for all $u, v \in V$
- $Se_1, ..., Se_n$ is orthonormal for every orthonormal list of vectors $e_1, ..., e_n$ in $V$
- There exists an orthonormal basis $e_1, ..., e_n$ of $V$ such that $S e_1, ..., S e_n$ is orthonormal
- $S^* S = I$
- $S S^* = I$
- $S^*$ is an isometry
- $S$ is invertible and $S^{-1} = S^*$

*** Theorem | Description of Isometries when $F = C$

Suppose $V$ is a complex inner product space and $S \in \mathcal{L}(V)$. Then the following are equivalent 

- $S$ is an isometry
- There is an orthonormal basis of $V$ consisting of eigenvectors of $S$ whose corresponding eigenvalues all have absolute value 1 

** Polar Decomposition and Singular Value Decomposition

*** Notation | $\sqrt{T}$

If $T$ is a positive operator, then $\sqrt{T}$ denotes the unique positive square root of $T$

*** Theorem | Polar Decomposition

Suppose $T \in \mathcal{L}(V)$. Then there exists an isometry $S \in \mathcal{L}(V)$ such that $T = S \sqrt{T^* T}$

*** Definition | Singular Values 

Suppose $T \in \mathcal{L}(V)$. The singular values of $T$ are the eigenvalues of $\sqrt{T^* T}$, with each eigenvalue $\lambda$ repeated dim $E(\lambda, \sqrt{T^* T})$ times where $E$ is the notation for an eigenspace. 


