* Linear Maps

Learning Objectives for this Chapter 
- Fundamental Theorem of Maps
- The matrix of a linear map with respect to given bases
- isomorphic vector spaces
- product spaces
- quotient spaces
- the dual space of a vector space and the dual of a linear map 

** 3.A | The Vector Space of Linear Maps 

*** Definition | Linear Map 

- A linear map from $V$ to $W$ is a function $T : V \to W$ with the following properties: 
  - additivity : $T(u + v) = Tu + Tv$ for all $u, v \in V$
  - homogeneity : $T(\lambda v) = \lambda(Tv)$ for all $\lambda \in F$ and all $v \in V$

The set of all linear maps from $V$ to $W$ is denoted $\mathcal{L}(V, W)$

*** Theorem | Linear Maps and Basis of Domain 

Suppose $v_1, ..., v_n$ is a basis of $V$ and $w_1, ..., w_n \in W$. Then there exists a unique linear map $T : V \to W$ such that $Tv_j = w_j$ for each $j = 1, ..., n$.

The existence part of this result means that we can find a linear map that takes on whatever values we wish on the vectors in a basis. The uniqueness part of the next result means that a linear map is completely determined by its values on a basis. 

*** Definition | Addition and Scalar Multiplication on $\mathcal{L}(V, W)$

Suppose $S, T \in \mathcal{L}(V, W)$ and $\lambda \in F$. The sum $S + T$ and the product $\lambda T$ are the linear maps from $V$ to $W$ defined by $(S + T)(v) = Sv + Tv$ and $(\lambda T)(v) = \lambda (Tv)$ for all $v \in V$. 

*** Theorem | $\mathcal{L}(V, W)$ is a vector space 

With the operations of addition and scalar multiplication as defined above, $\mathcal{L}(V, W)$ is a vector space. 

*** Definition | Product of Linear Maps 

If $T \in \mathcal{L}(U, V)$ and $S \in \mathcal{L}(V, W)$, then the product $ST \in \mathcal{L}(U, W)$ is defined by $(ST)(u) = S(Tu)$ for $u \in U$

*** Algebraic Properties of Products of Linear Maps 

- Associativity : $(T_1 T_2)T_3 = T_1 (T_2 T_3)$ whenever $T_1, T_2, T_3$ are linear maps such that the products make sense.
- Identity : $TI = IT = T$ whenever $T \in \mathcal{L}(V, W)$
- Distributive Properties : $(S_1 + S_2)T = S_1T + S_2T$ and $S(T_1 + T_2) = ST_1 + ST_2$ whenever $T, T_1, T_2 \in \mathcal{L}(U, V)$ and $S, S_1, S_2 \in \mathcal{L}(V, W)$

Multiplication of linear maps is not commutative. In other words, it is not necessarily true that $ST = TS$, even if both sides of the equation make sense. 

*** Theorem | Linear Maps take 0 to 0 

Suppose $T: V \to W$. Then $T(0) = 0$.

** 3.B | Null Spaces and Ranges

*** Definition |  null space, null $T$

For $T \in \mathcal{L}(V, W)$, the null space of $T$, denoted null $T$, is the subset of $V$ consisting of those vectors that $T$ maps to 0:

null $T = \{v \in V : Tv = 0\}$

*** Theorem | The null space is a subspace 

Suppose $T \in \mathcal{L}(V, W)$. Then null $T$ is a subspace of $V$

*** Definition | Injective 

A function $T : V \to W$ is called injective if $Tu = Tv$ implies $u = v$. 

Many mathematicians use the term one-to-one, which means the same thing. In other words, $T$ is injective if it maps distinct inputs to distinct outputs. 

*** Theorem | Injectivity is equivalent to null space equals {0}

Let $T \in \mathcal{L}(V, W)$. Then $T$ is injective iff null $T = \{0\}$.

This says that we can check whether a linear map is injective by checking whether 0 is the only vector that gets mapped to 0. 

*** Definition | Range 

For $T$ a function from $V$ to $W$, the range of $T$ is the subset of $W$ consisting of those vectors that are of the form $Tv$ for some $v \in V$. 

range $T = \{Tv : v \in V\}$

Some mathematicians use the word image, which means the same as range. 

*** Theorem | The range is a subspace 

If $T \in \mathcal{L}(V, W)$, then range $T$ is a subspace of $W$

This shows that the range of each linear map is a subspace of the vector space into which it is being mapped

*** Definition | Surjective 

A function $T : V \to W$ is called surjective if its range equals $W$

Many mathematicians use the term onto, which means the same as surjective. 

*** Theorem | Fundamental Theorem of Linear Maps 

Suppose $V$ is finite-dimensional and $T \in \mathcal{L}(V, W)$. Then the range $T$ is finite-dimensional and dim $V$ = dim null $T$ + dim range $T$

*** Theorem | A map to a smaller dimensional space is not injective 

Suppose $V$ and $W$ are finite-dimensional vector spaces such that dim $V$ > dim $W$. Then no linear map from $V$ to $W$ is injective. 

*** Theorem | A map to a larger dimensional space is not surjective 

Suppose $V$ and $W$ are finite-dimensional vector spaces such that dim $V$ < dim $W$. Then no linear map from $V \to W$ is surjective

*** Theorem | Homogeneous System of Linear Equations

A homogeneous system of linear equations with more variables than equations has nonzero solutions 

*** Theorem | Inhomogeneous System of Linear Equations 

An inhomogeneous system of linear equations with more equations than variables has no solution for some choice of the constant terms

** 3.C | Matrices 

*** Definition | matrix $A_{j, k}$

Let $m, n$ denote positive integers. An $m$ - by - $n$ matrix $A$ is a rectangular array of elements of $F$ with $m$ rows and $n$ columns: 

 $A = \begin{pmatrix} a_{1, 1} & \cdots & a_{1, n} \\ \vdots &  & \vdots \\ a_{n, 1} & \cdots & a_{n, n} \end{pmatrix}$

*** Definition | matrix of a linear map $\mathcal{M}(T)$

Suppose $T \in \mathcal{L}(V, W)$ and $v_1, ..., v_n$ is a basis of $V$ and $w_1, ..., w_m$ is a basis of $W$. The matrix of $T$ with respect to these bases is the m-by-n matrix $\mathcal{M}(T)$ whose entries $A_{j,k}$ are defined by $Tv_k = A_{1, k} w_1 + ... + A_{m, k} w_m$. If the bases are not clear from the context, then the notation $\mathcal{M}(T, (v_1, ..., v_n), (w_1, ..., w_m))$ is used. 

*** Definition | Matrix Addition 

The sum of two matrices of the same size is the matrix obtained by adding the corresponding entries in their matrices: 

$\begin{pmatrix} a_{1, 1} & \cdots & a_{1, n} \\ \vdots &  & \vdots \\ a_{n, 1} & \cdots & a_{n, n} \end{pmatrix} + \begin{pmatrix} b_{1, 1} & \cdots & b_{1, n} \\ \vdots &  & \vdots \\ b_{n, 1} & \cdots & b_{n, n} \end{pmatrix} = \begin{pmatrix} a_{1, 1} + b_{1, 1} & \cdots & a_{1, n} + b_{1, n} \\ \vdots &  & \vdots \\ a_{n, 1} + b_{n, 1} & \cdots & a_{n, n} + b_{n, n} \end{pmatrix}$

In other words, $(A + C)_{j, k} = A_{j, k} + C_{j, k}$. 

*** Theorem | The matrix of the sum of linear maps 

Suppose $S, T \in \mathcal{L}(V, W)$. Then $\mathcal{M}(S + T) = \mathcal{M}(S) + \mathcal{M}(T)$

*** Definition | Scalar multiplication of a matrix 

$\lambda \begin{pmatrix} a_{1, 1} & \cdots & a_{1, n} \\ \vdots &  & \vdots \\ a_{n, 1} & \cdots & a_{n, n} \end{pmatrix} = \begin{pmatrix}  \lambda a_{1, 1} & \cdots &  \lambda a_{1, n} \\ \vdots &  & \vdots \\  \lambda a_{n, 1} & \cdots &  \lambda a_{n, n} \end{pmatrix}$

In other words, $(\lambda A_{j, k}) = \lambda A_{j, k}$

*** Theorem | The matrix of a scalar times a linear map

Suppose $\lambda \in F$ and $T \in \mathcal{L}(V, W)$. Then $\mathcal{M}(\lambda T) = \lambda \mathcal{M}(T)$

*** Theorem | dim $F^{m, n} = mn$

Suppose $m$ and $n$ are positive integers. With addition and scalar multiplcation defined as above, $F^{m, n}$ is a vector space with dimension $mn$. 

*** Definition | Matrix Multiplication 

Suppose $A$ is an m-by-n matrix and $C$ is an n-by-p matrix. Then $AC$ is defined to be the m-by-p matrix whose entry in row $j$, column $k$, is given by the following equation : 

$(AC)_{j, k} = \sum_{r = 1}^n A_{j, r}C_{r, k}$

In other words, the entry in row $j$, column $k$, of $AC$ is computed by taking row $j$ of $A$ and column $k$ of $C$, multiplying together corresponding entires, and then summing. 

*** Theorem | The matrix of the product of linear maps 

If $T \in \mathcal{L}(U, V)$ and $S \in \mathcal{L}(V, W)$, then $\mathcal{M}(ST) = \mathcal{M}(S)\mathcal{M}(T)$

*** Theorem | Entry of matrix product equals row times column 

Suppose $A$ is an m-by-n matrix and $C$ is an n-by-p matrix. Then $(AC)_{j, k} = A_{j,.} C_{.,k}$ for $1 \leq j \leq m$ and $1 \leq k \leq p$

*** Theorem | Column of matrix product equals matrix times column 

Suppose $A$ is an m by n matrix and $C$ is an n by p matrix. Then $(AC)_{., k} = AC_{., k}$ for $1 \leq k \leq p$.

*** Theorem | Linear Combination of Columns 

Suppose $A$ is an m by n matrix and $c = \begin{pmatrix}c_1 \\ \vdots \\ c_n \end{pmatrix}$ is an n by 1 matrix. Then $Ac = c_1 A_{., 1} + ... + c_n A_{., n}$. In other words, $Ac$ is a linear combination of the columns of $A$, with the scalars that multiply the columns coming from $c$. 

** 3.D | Invertibility and Isomorphic Vector Spaces

*** Definition | Invertible, Inverse 

- A linear map $T \in \mathcal{L}(V, W)$ is called invertible if there exists a linear map $S \in \mathcal{L}(W, V)$ such that $ST$ equals the identity map on $V$ and $TS$ equals the identity map on $W$. 
- A linear map $S \in \mathcal{L}(W, V)$ satisfying $ST = I$ and $TS = I$ is called an inverse of $T$

*** Theorem | Inverse is unique 

An invertible linear map has a unique inverse 

*** Theorem | Invertibility is equivalent to injectivity and surjectivity 

A linear map is invertible iff it is injective and surjective 


*** Definition | isomorphism, isomorphic 

- An isomorphism is an invertible linear map
- Two vector spaces are called isomorphic if there is an isomorphism from one vector space onto the other one

*** Theorem | Dimension shows whether vector spaces are isomorphic 

Two finite-dimensional vector spaces over $F$ are isomorphic iff they have the same dimension 


