* Linear Maps

Learning Objectives for this Chapter 
- Fundamental Theorem of Maps
- The matrix of a linear map with respect to given bases
- isomorphic vector spaces
- product spaces
- quotient spaces
- the dual space of a vector space and the dual of a linear map 

** 3.A | The Vector Space of Linear Maps 

*** Definition | Linear Map 

- A linear map from $V$ to $W$ is a function $T : V \to W$ with the following properties: 
  - additivity : $T(u + v) = Tu + Tv$ for all $u, v \in V$
  - homogeneity : $T(\lambda v) = \lambda(Tv)$ for all $\lambda \in F$ and all $v \in V$

The set of all linear maps from $V$ to $W$ is denoted $\mathcal{L}(V, W)$

*** Theorem | Linear Maps and Basis of Domain 

Suppose $v_1, ..., v_n$ is a basis of $V$ and $w_1, ..., w_n \in W$. Then there exists a unique linear map $T : V \to W$ such that $Tv_j = w_j$ for each $j = 1, ..., n$.

The existence part of this result means that we can find a linear map that takes on whatever values we wish on the vectors in a basis. The uniqueness part of the next result means that a linear map is completely determined by its values on a basis. 

*** Definition | Addition and Scalar Multiplication on $\mathcal{L}(V, W)$

Suppose $S, T \in \mathcal{L}(V, W)$ and $\lambda \in F$. The sum $S + T$ and the product $\lambda T$ are the linear maps from $V$ to $W$ defined by $(S + T)(v) = Sv + Tv$ and $(\lambda T)(v) = \lambda (Tv)$ for all $v \in V$. 

*** Theorem | $\mathcal{L}(V, W)$ is a vector space 

With the operations of addition and scalar multiplication as defined above, $\mathcal{L}(V, W)$ is a vector space. 

*** Definition | Product of Linear Maps 

If $T \in \mathcal{L}(U, V)$ and $S \in \mathcal{L}(V, W)$, then the product $ST \in \mathcal{L}(U, W)$ is defined by $(ST)(u) = S(Tu)$ for $u \in U$

*** Algebraic Properties of Products of Linear Maps 

- Associativity : $(T_1 T_2)T_3 = T_1 (T_2 T_3)$ whenever $T_1, T_2, T_3$ are linear maps such that the products make sense.
- Identity : $TI = IT = T$ whenever $T \in \mathcal{L}(V, W)$
- Distributive Properties : $(S_1 + S_2)T = S_1T + S_2T$ and $S(T_1 + T_2) = ST_1 + ST_2$ whenever $T, T_1, T_2 \in \mathcal{L}(U, V)$ and $S, S_1, S_2 \in \mathcal{L}(V, W)$

Multiplication of linear maps is not commutative. In other words, it is not necessarily true that $ST = TS$, even if both sides of the equation make sense. 

*** Theorem | Linear Maps take 0 to 0 

Suppose $T: V \to W$. Then $T(0) = 0$.

** 3.B | Null Spaces and Ranges

*** Definition |  null space, null $T$

For $T \in \mathcal{L}(V, W)$, the null space of $T$, denoted null $T$, is the subset of $V$ consisting of those vectors that $T$ maps to 0:

null $T = \{v \in V : Tv = 0\}$

*** Theorem | The null space is a subspace 

Suppose $T \in \mathcal{L}(V, W)$. Then null $T$ is a subspace of $V$

*** Definition | Injective 

A function $T : V \to W$ is called injective if $Tu = Tv$ implies $u = v$. 

Many mathematicians use the term one-to-one, which means the same thing. In other words, $T$ is injective if it maps distinct inputs to distinct outputs. 

*** Theorem | Injectivity is equivalent to null space equals {0}

Let $T \in \mathcal{L}(V, W)$. Then $T$ is injective iff null $T = \{0\}$.

This says that we can check whether a linear map is injective by checking whether 0 is the only vector that gets mapped to 0. 

*** Definition | Range 

For $T$ a function from $V$ to $W$, the range of $T$ is the subset of $W$ consisting of those vectors that are of the form $Tv$ for some $v \in V$. 

range $T = \{Tv : v \in V\}$

Some mathematicians use the word image, which means the same as range. 

*** Theorem | The range is a subspace 

If $T \in \mathcal{L}(V, W)$, then range $T$ is a subspace of $W$

This shows that the range of each linear map is a subspace of the vector space into which it is being mapped

*** Definition | Surjective 

A function $T : V \to W$ is called surjective if its range equals $W$

Many mathematicians use the term onto, which means the same as surjective. 

*** Theorem | Fundamental Theorem of Linear Maps 

Suppose $V$ is finite-dimensional and $T \in \mathcal{L}(V, W)$. Then the range $T$ is finite-dimensional and dim $V$ = dim null $T$ + dim range $T$

*** Theorem | A map to a smaller dimensional space is not injective 

Suppose $V$ and $W$ are finite-dimensional vector spaces such that dim $V$ > dim $W$. Then no linear map from $V$ to $W$ is injective. 

*** Theorem | A map to a larger dimensional space is not surjective 

Suppose $V$ and $W$ are finite-dimensional vector spaces such that dim $V$ < dim $W$. Then no linear map from $V \to W$ is surjective

*** Theorem | Homogeneous System of Linear Equations

A homogeneous system of linear equations with more variables than equations has nonzero solutions 

*** Theorem | Inhomogeneous System of Linear Equations 

An inhomogeneous system of linear equations with more equations than variables has no solution for some choice of the constant terms

** 3.C | Matrices 

*** Definition | matrix $A_{j, k}$

Let $m, n$ denote positive integers. An $m$ - by - $n$ matrix $A$ is a rectangular array of elements of $F$ with $m$ rows and $n$ columns: 

 $A = \begin{pmatrix} a_{1, 1} & \cdots & a_{1, n} \\ \vdots &  & \vdots \\ a_{n, 1} & \cdots & a_{n, n} \end{pmatrix}$

*** Definition | matrix of a linear map $\mathcal{M}(T)$

Suppose $T \in \mathcal{L}(V, W)$ and $v_1, ..., v_n$ is a basis of $V$ and $w_1, ..., w_m$ is a basis of $W$. The matrix of $T$ with respect to these bases is the m-by-n matrix $\mathcal{M}(T)$ whose entries $A_{j,k}$ are defined by $Tv_k = A_{1, k} w_1 + ... + A_{m, k} w_m$. If the bases are not clear from the context, then the notation $\mathcal{M}(T, (v_1, ..., v_n), (w_1, ..., w_m))$ is used. 

*** Definition | Matrix Addition 

The sum of two matrices of the same size is the matrix obtained by adding the corresponding entries in their matrices: 

$\begin{pmatrix} a_{1, 1} & \cdots & a_{1, n} \\ \vdots &  & \vdots \\ a_{n, 1} & \cdots & a_{n, n} \end{pmatrix} + \begin{pmatrix} b_{1, 1} & \cdots & b_{1, n} \\ \vdots &  & \vdots \\ b_{n, 1} & \cdots & b_{n, n} \end{pmatrix} = \begin{pmatrix} a_{1, 1} + b_{1, 1} & \cdots & a_{1, n} + b_{1, n} \\ \vdots &  & \vdots \\ a_{n, 1} + b_{n, 1} & \cdots & a_{n, n} + b_{n, n} \end{pmatrix}$

In other words, $(A + C)_{j, k} = A_{j, k} + C_{j, k}$. 

*** Theorem | The matrix of the sum of linear maps 

Suppose $S, T \in \mathcal{L}(V, W)$. Then $\mathcal{M}(S + T) = \mathcal{M}(S) + \mathcal{M}(T)$

*** Definition | Scalar multiplication of a matrix 

$\lambda \begin{pmatrix} a_{1, 1} & \cdots & a_{1, n} \\ \vdots &  & \vdots \\ a_{n, 1} & \cdots & a_{n, n} \end{pmatrix} = \begin{pmatrix}  \lambda a_{1, 1} & \cdots &  \lambda a_{1, n} \\ \vdots &  & \vdots \\  \lambda a_{n, 1} & \cdots &  \lambda a_{n, n} \end{pmatrix}$

In other words, $(\lambda A_{j, k}) = \lambda A_{j, k}$

*** Theorem | The matrix of a scalar times a linear map

Suppose $\lambda \in F$ and $T \in \mathcal{L}(V, W)$. Then $\mathcal{M}(\lambda T) = \lambda \mathcal{M}(T)$

*** Theorem | dim $F^{m, n} = mn$

Suppose $m$ and $n$ are positive integers. With addition and scalar multiplcation defined as above, $F^{m, n}$ is a vector space with dimension $mn$. 

*** Definition | Matrix Multiplication 

Suppose $A$ is an m-by-n matrix and $C$ is an n-by-p matrix. Then $AC$ is defined to be the m-by-p matrix whose entry in row $j$, column $k$, is given by the following equation : 

$(AC)_{j, k} = \sum_{r = 1}^n A_{j, r}C_{r, k}$

In other words, the entry in row $j$, column $k$, of $AC$ is computed by taking row $j$ of $A$ and column $k$ of $C$, multiplying together corresponding entires, and then summing. 

*** Theorem | The matrix of the product of linear maps 

If $T \in \mathcal{L}(U, V)$ and $S \in \mathcal{L}(V, W)$, then $\mathcal{M}(ST) = \mathcal{M}(S)\mathcal{M}(T)$

*** Theorem | Entry of matrix product equals row times column 

Suppose $A$ is an m-by-n matrix and $C$ is an n-by-p matrix. Then $(AC)_{j, k} = A_{j,.} C_{.,k}$ for $1 \leq j \leq m$ and $1 \leq k \leq p$

*** Theorem | Column of matrix product equals matrix times column 

Suppose $A$ is an m by n matrix and $C$ is an n by p matrix. Then $(AC)_{., k} = AC_{., k}$ for $1 \leq k \leq p$.

*** Theorem | Linear Combination of Columns 

Suppose $A$ is an m by n matrix and $c = \begin{pmatrix}c_1 \\ \vdots \\ c_n \end{pmatrix}$ is an n by 1 matrix. Then $Ac = c_1 A_{., 1} + ... + c_n A_{., n}$. In other words, $Ac$ is a linear combination of the columns of $A$, with the scalars that multiply the columns coming from $c$. 

** 3.D | Invertibility and Isomorphic Vector Spaces

*** Definition | Invertible, Inverse 

- A linear map $T \in \mathcal{L}(V, W)$ is called invertible if there exists a linear map $S \in \mathcal{L}(W, V)$ such that $ST$ equals the identity map on $V$ and $TS$ equals the identity map on $W$. 
- A linear map $S \in \mathcal{L}(W, V)$ satisfying $ST = I$ and $TS = I$ is called an inverse of $T$

*** Theorem | Inverse is unique 

An invertible linear map has a unique inverse 

*** Theorem | Invertibility is equivalent to injectivity and surjectivity 

A linear map is invertible iff it is injective and surjective 

*** Definition | isomorphism, isomorphic 

- An isomorphism is an invertible linear map
- Two vector spaces are called isomorphic if there is an isomorphism from one vector space onto the other one

*** Theorem | Dimension shows whether vector spaces are isomorphic 

Two finite-dimensional vector spaces over $F$ are isomorphic iff they have the same dimension 

If $v_1, ..., v_n$ is a basis of $V$ and $w_1, ..., w_m$ is a basis of $W$, then for each $T \in \mathcal{L}(V, W)$, we have a matrix $\mathcal{M}(T) \in F^{m, n}$. In other words, once bases have been fixed for $V$ and $W$, $\mathcal{M}$ becomes a function s.t. $\mathcal{M}: \mathcal{L}(V, W) \to F^{m, n}$. 

*** Theorem | $\mathcal{L}(V, W)$ and $F^{m, n}$ are isomorphic.

Suppose $v_1, ..., v_n$ is a basis of $V$ and $w_1, ..., w_m$ is a basis of $W$. Then $\mathcal{M}$ is an isomorphism between $\mathcal{L}(V, W)$ and $F^{m, n}$

*** Theorem | dim $\mathcal{L}(V, W) =$ (dim $V$)(dim $W$) 

Suppose $V$ and $W$ are finite-dimensional. Then $\mathcal{L}(V, W)$ is finite-dimensional and dim $\mathcal{L}(V, W)$ = (dim $V$)(dim $W$)

*** Definition | matrix of a vector $\mathcal{M}(v)$

Suppose $v \in V$ and $v_1, ..., v_n$ is a basis of $V$. The matrix of $v$ with respect to this basis is the n-by-1 matrix $\mathcal{M}(v) = \begin{pmatrix} c_1 \\ \vdots \\ c_n \end{pmatrix}$

where $c_1, ..., c_n$ are the scalars such that $v = c_1 v_1 + ... + c_n v_n$.

*** Theorem | $\mathcal{M}(T)_{., k} = \mathcal{M}(v_k)$

Where $\mathcal{M}(v_k)$ is computed with respect to the basis $w_1, ..., w_m$ of $W$

Suppose $T \in \mathcal{L}(V, W)$ and $v_1, ..., v_n$ is a basis of $V$ and $w_1, ..., w_m$ is a basis of $W$. Let $1 \leq k \leq n$. Then the $k^{th}$ column of $\mathcal{M}(T)$, which is denoted by $\mathcal{M}(T)_{., k}$ equals $\mathcal{M}(v_k)$.  

*** Theorem | Linear Maps act like Matrix Multiplication 

Suppose $T \in \mathcal{L}(V, W)$ and $v \in V$. Suppose $v_1, ..., v_n$ is a basis of $V$ and $w_1, ..., w_m$ is a basis of $W$. Then $\mathcal{M}(Tv) = \mathcal{M}(T)\mathcal{M}(v)$

*** Definition | Operator $\mathcal{L}(V)$

- A linear map from a vector space to itself is called an operator
- The notation $\mathcal{L}(V)$ denotes the set of all operators on $V$. In other words, $\mathcal{L}(V) = \mathcal{L}(V, V)$. 

*** Theorem | Injectivity is equivalent to surjectivity in finite dimensions 

Suppose $V$ is finite-dimensional and $T \in \mathcal{L}(V)$. Then the following are equivalent:

- $T$ is invertible
- $T$ is injective
- $T$ is surjective 

** 3.E | Products and Quotients of Vector Spaces

*** Definition | Product of Vector Spaces 

Suppose $V_1, ..., V_m$ are vector spaces over $F$. 
+ The product $V_1 \times ... \times V_m$ is defined by $V_1 \times ... \times V_m = \{(v_1, ..., v_m) : v_1 \in V_1, ..., v_m \in V_m\}$
+ Addition on $V_1 \times ... \times V_m$ is defined by $(u_1, ..., u_m) + (v_1, ..., v_m) = (u_1 + v_1, ..., u_m + v_m)$
+ Scalar multiplication on $V_1 \times ... \times V_m$ is defined by $\lambda (v_1, ..., v_m) = (\lambda v_1, ..., \lambda v_m)$

*** Theorem | Product of Vector Spaces is a Vector Space 

Suppose $V_1, ..., V_m$ are vector spaces over $F$. Then $V_1 \times ... \times V_m$ is a vector space over $F$

*** Theorem | Dimension of a product is the sum of dimensions

Suppose $V_1, ..., V_m$ are finite dimensional vector spaces. Then $V_1 \times ... \times V_m$ is finite-dimensional and dim $(V_1 \times ... \times V_m)$ = dim$V_1$ + ... + dim$V_m$. 


*** Theorem | Products and Direct Sums 

Suppose that $U_1, ..., U_m$ are subspaces of $V$. Define a linear map $\Gamma : U_1 \times ... \times U_m \to U_1 + ... + U_m$ by $\Gamma(u_1, ..., u_m) = u_1 + ... + u_m$.

Then $U_1 + ... + U_m$ is a direct sum iff $\Gamma$ is injective. 

*** Theorem | A sum is a direct sum iff dimensions add up

Suppose $V$ is finite-dimensional and $U_1, ..., U_m$ are subspaces of $V$. Then $U_1 + ... + U_m$ is a direct sum iff

dim$(U_1 + ... + U_m)$ = dim $U_1 + ... +$ dim $U_m$

*** Definition | $v + U$

Suppose $v \in V$ and $U$ is a subspace of $V$. Then $v + U$ is the subset of $V$ defined by $v + U = \{v + u : u \in U\}$. 

*** Definition | Affine Subset, Parallel 

- An affine subset of $V$ is a subset of $V$ of the form $v + U$ for some $v \in V$ and some subspace $U$ of $V$.
- For $v \in V$ and $U$ a subspace of $V$, the affine subset $v + U$ is said to be parallel to $U$

*** Definition | Quotient Space $V / U$

Suppose $U$ is a subspace of $V$. Then the quotient space $V / U$ is the set of all affine subsets of $V$ parallel to $U$. In other words, $V/U = \{v + U : v \in V\}$

*** Theorem | Two affine subsets parallel to $U$ are equal or disjoint 

Suppose $U$ is a subspace of $V$ and $v, w \in V$. Then the following are equivalent:

- $v - w \in U$
- $v + U = w + U$
- $(v + U) \cap (w + U) \neq \emptyset$

*** Definition | Addition and Scalar Multiplication on $V / U$

Suppose $U$ is a subspace of $V$. Then addition and scalar multiplication are defined on $V / U$ by

$(v + U) + (w + U) = (v + w) + U$
$\lambda (v + U) = (\lambda v) + U$

for $v, w \in V$ and $\lambda \in F$

*** Theorem | Quotient Space is a Vector Space 

Suppose $U$ is a subspace of $V$. Then $V / U$, with the operations of addition and scalar multiplication as defined above, is a vector space. 

*** Definition | Quotient Map $\pi$

Suppose $U$ is a subspace of $V$. The quotient map $\pi$ is the linear map $\pi : V \to V / U$ is defined by $\pi(v) = v + U$ for $v \in V$. 

*** Theorem | Dimension of a Quotient Space 

Suppose $V$ is finite-dimensional and $U$ is a subspace of $V$. Then dim $V/U$ = dim $V$ - dim $U$

*** Definition | $\tilde{T}$

Suppose $T \in \mathcal{L}(V, W)$. Define $\tilde{T} : V / (null T) \to W$ by $\tilde{T}(v + nullT) = Tv$

*** Theorem | Null Space and Range of $\tilde{T}$

Suppose $T \in \mathcal{L}(V, W)$. Then 

- $\tilde{T}$ is a linear map from $V / (null T)$ to $W$
- $\tilde{T}$ is injective
- range $\tilde{T}$ = range $T$
- $V / (null T)$ is isomorphic to range $T$

** 3.F | Duality

Linear maps into the scalar field $F$ play a special role in linear algebra, and thus get a special name: 

*** Definition | Linear Functional 

A linear functional on $V$ is a linear map from $V \to F$. In other words, a linear functional is an element of $\mathcal{L}(V, F)$. 

*** Definition | dual space $V'$

The dual space of $V$, denoted $V'$, is the vector space of all linear functionals on $V$. In other words, $V' = \mathcal{L}(V, F)$. 

*** Theorem | dim $V'$ = dim $V$

Suppose $V$ is finite dimensional. Then $V'$ is also finite-dimensional and dim $V'$ = dim $V$.

This follows from dim $\mathcal{L}(V, W)$ = $(dim V)(dim W)$

*** Definition | Dual Basis 

If $v_1, ..., v_n$ is a basis of $V$, then the dual basis of $v_1, ..., v_n$ is the list $\phi_1, ..., \phi_n$ of elements of $V'$ where each $\phi_j$ is the linear functional on $V$ such that $\phi_j(v_k) = 1$ if $k = j$, and 0 otherwise.

*** Theorem | Dual Basis is a Basis of the Dual Space 

Suppose $V$ is finite-dimensional. Then the dual basis of a basis of $V$ is a basis of $V'$. 

*** Definition | dual map $T'$

If $T \in \mathcal{L}(V, W)$, then the dual map of $T$ is the linear map $T' \in \mathcal{L}(W', V')$ defined by $T'(\phi) = \phi \circ T$ for $\phi \in W'$ 

*** Theorem | Algebraic Properties of Dual Maps 

- $(S + T)' = S' + T'$ for all $S, T \in \mathcal{L}(V, W)$
- $(\lambda T)' = \lambda T'$ for all $\lambda \in F$ and all $T \in \mathcal{L}(V, W)$
- $(ST)' = T'S'$ for all $T \in \mathcal{L}(U, W)$ and all $S \in \mathcal{L}(V, W)$


