* Linear Maps

Learning Objectives for this Chapter 
- Fundamental Theorem of Maps
- The matrix of a linear map with respect to given bases
- isomorphic vector spaces
- product spaces
- quotient spaces
- the dual space of a vector space and the dual of a linear map 

** The Vector Space of Linear Maps 

*** Definition | Linear Map 

- A linear map from $V$ to $W$ is a function $T : V \to W$ with the following properties: 
  - additivity : $T(u + v) = Tu + Tv$ for all $u, v \in V$
  - homogeneity : $T(\lambda v) = \lambda(Tv)$ for all $\lambda \in F$ and all $v \in V$

The set of all linear maps from $V$ to $W$ is denoted $\mathcal{L}(V, W)$

*** Theorem | Linear Maps and Basis of Domain 

Suppose $v_1, ..., v_n$ is a basis of $V$ and $w_1, ..., w_n \in W$. Then there exists a unique linear map $T : V \to W$ such that $Tv_j = w_j$ for each $j = 1, ..., n$.

The existence part of this result means that we can find a linear map that takes on whatever values we wish on the vectors in a basis. The uniqueness part of the next result means that a linear map is completely determined by its values on a basis. 

*** Definition | Addition and Scalar Multiplication on $\mathcal{L}(V, W)$

Suppose $S, T \in \mathcal{L}(V, W)$ and $\lambda \in F$. The sum $S + T$ and the product $\lambda T$ are the linear maps from $V$ to $W$ defined by $(S + T)(v) = Sv + Tv$ and $(\lambda T)(v) = \lambda (Tv)$ for all $v \in V$. 

*** Theorem | $\mathcal{L}(V, W)$ is a vector space 

With the operations of addition and scalar multiplication as defined above, $\mathcal{L}(V, W)$ is a vector space. 

*** Definition | Product of Linear Maps 

If $T \in \mathcal{L}(U, V)$ and $S \in \mathcal{L}(V, W)$, then the product $ST \in \mathcal{L}(U, W)$ is defined by $(ST)(u) = S(Tu)$ for $u \in U$

*** Algebraic Properties of Products of Linear Maps 

- Associativity : $(T_1 T_2)T_3 = T_1 (T_2 T_3)$ whenever $T_1, T_2, T_3$ are linear maps such that the products make sense.
- Identity : $TI = IT = T$ whenever $T \in \mathcal{L}(V, W)$
- Distributive Properties : $(S_1 + S_2)T = S_1T + S_2T$ and $S(T_1 + T_2) = ST_1 + ST_2$ whenever $T, T_1, T_2 \in \mathcal{L}(U, V)$ and $S, S_1, S_2 \in \mathcal{L}(V, W)$

Multiplication of linear maps is not commutative. In other words, it is not necessarily true that $ST = TS$, even if both sides of the equation make sense. 

*** Theorem | Linear Maps take 0 to 0 

Suppose $T: V \to W$. Then $T(0) = 0$.
