* Polynomials 

Learning Objectives for this Chapter: 
- Division Algorithm for Polynomials
- factorization of polynomials over $C$ 
- factorization of polynomials over $R$ 

** 4.A | Polynomials 

This chapter is 1 section. 

*** Definition re $z$, Im $z$

Suppose $z = a + bi$, where $a, b \in R$. 
- The real part of $z$, denoted Re $z$, is defined by Re $z = a$
- The imaginary part of $z$, denoted Im $z$, is defined by Im $z = b$

*** Definition | complex conjugate $\bar{z}$, absolute value $|z|$

Suppose $z \in C$. 

- The complex conjugate of $z \in C$, denoted $\bar{z}$, is defined by $\bar{z} =$ Re $z$ - (Im $z$)$i$
- The absolute value of a complex number $z$, denoted $|z|$, is defined by $|z| = \sqrt{(\mathrm{Re}z)^2 + (\mathrm{Im}z)^2}$

*** Theorem | Properties of Complex Numbers 

Suppose $w, z \in C$. Then 

- sum of $z$ and $\bar{z}$ 
  - $z + \bar{z} = 2 \mathrm{Re}z$

- difference of $z$ and $\bar{z}$
  - $z - \bar{z} = 2 \mathrm{Im}zi$

- product of $z$ and $\bar{z}$
  - $z\bar{z} = |z|^2$

- Additivity and Multiplicativity of Complex Conjugate 
  - $\bar{w + z} = \bar{w} + \bar{z}$ and $\bar{wz} = \bar{w}\bar{z}$

- conjugate of conjugate 
  - $\bar{\bar{z}} = z$

- real and imaginary parts are bounded by $|z|$
  - $|\mathrm{Re} z| \leq |z|$ and $|\mathrm{Im}z| \leq |z|$

- Absolute value of the complex conjugate 
  - $|\bar{z}| = |z|$

- multiplicativity of absolute value 
  - $|wz| = |w||z|$

- Triangle Inequality 
  - $|w + z| \leq |w| + |z|$

*** Theorem | If a polynomial is the zero function, then all coefficients are 0 

Suppose $a_0, ..., a_m \in F$. If $a_0 + a_1z + ... + a_mz^m = 0$ for every $z \in F$, then $a_0 = ... = a_m = 0$

This result implies that the coefficients of a polynomial are uniquely determined (because if a polynomial had two different sets of coefficients, then subtracting the two representations of the polynomial would give a contradiction to the result above). 

*** Theorem | Division Algorithm for Polynomials 

Suppose that $p, s \in \mathcal{P}(F)$, with $s \neq 0$. Then there exist unique polynomials with $q, r \in \mathcal{P}(F)$ such that $p = sq + r$ and deg $r <$ deg $s$

*** Definition | Zero of a Polynomial 

A number $\lambda \in F$ is called a zero (or root) of a polynomial $p \in \mathcal{P}(F)$ if $p(\lambda) = 0$. 

*** Definition | Factor

A polynomial $s \in \mathcal{P}(F)$ is called a factor of $p \in \mathcal{P}(F)$ if there exists a polynomial $q \in \mathcal{P}(F)$ such that $p = sq$

*** Theorem | Each zero of a polynomial corresponds to a degree-1 factor 

Suppose $p \in \mathcal{P}(F)$ and $\lambda \in F$. Then $p(\lambda) = 0$ iff there is a polynomial $q \in \mathcal{P}(F)$ such that $p(z) = (z - \lambda)q(z)$ for every $z \in F$. 

*** Theorem | A polynomial has at most as many zeros as its degree 

Suppose $p \in \mathcal{P}(F)$ is a polynomial with degree $m \geq 0$. Then $p$ has at most $m$ distinct zeros in $F$. 

*** Theorem | Fundamental Theorem of Algebra 

Every nonconstant polynomial with complex coefficients has a zero 

*** Theorem | Factorization of a Polynomial Over $C$

If $p \in \mathcal{P}(C)$ is a nonconstant polynomial, then $p$ has a unique factorization (except for the order of the factors) of the form $p(z) = c(z - \lambda_1)...(z - \lambda_m)$ where $c, \lambda_1, ..., \lambda_m \in C$

*** Theorem | Polynomials with real coefficients have zeros in pairs 

Suppose $p \in \mathcal{P}(C)$ is a polynomial with real coefficients. If $\lambda \in C$ is a zero of $p$, then so is $\bar{\lambda}$

*** Theorem | Factorization of a Quadratic Polynomial 

Suppose $b, c \in R$. Then there is a polynomial factorization of the form $x^2 + bx + c = (x - \lambda_1)(x - \lambda_2)$ with $\lambda_1, \lambda_2 \in R$ iff $b^2 \geq 4c$

*** Theorem | Factorization of a Polynomial over $R$

Suppose $p \in \mathcal{P}$ is a nonconstant polynomial. Then $p$ has a unique factorization (except for the order of the factors) of the form 
$p(x) = c(x - \lambda_1)...(x - \lambda_m)(x^2 + b_1x + c_1)...(x^2 + b_Mx + c_M)$, where $c, \lambda_1, ..., \lambda_m, b_1, ..., b_M, c_1, ..., c_M \in R$ with $b_j^2 < 4c_j$ for each $j$. 

