* Vector Spaces

Linear algebra is the study of linear maps on finite dimensional vector spaces. In this chapter we will define vector spaces and discuss their elementary properties. 

Learning objectives for this chapter:
- basic properties of complex numbers
- $\mathcal{R}^n$ and $\mathcal{C}^n$
- vector spaces
- subspaces
- sums and direct sums of subspaces

** 1.A | $\mathcal{R}^n$ and $\mathcal{C}^n$ 

*** Definition | Complex Numbers

- A complex number is an ordered pair $(a, b)$ where $a, b \in R$, but we will write this as $a + bi$
- The set of all complex numbers is denoted by $C = \{a + bi : a,b \in R\}$
- Addition and multiplcation on $C$
  - $(a + bi) + (c + di) = (a + c) + (b + d)i$
  - $(a + bi)(c + di) = (ac - bd) + (ad + dc)i$
  - $a, b, c, d \in R$

Properties of Complex Arithmetic 

- commutativity
  - $\alpha + \beta = \beta + \alpha$
- associtivity
  - $\alpha + (\beta + \lambda) = (\alpha + \beta) + \lambda$
- identities
  - $\lambda + 0 = \lambda$ 
- additive inverse
  - for every $\alpha \in C$, there exists a unique $\beta \in C$ s.t. $\alpha + \beta = 0$  
- multiplicative inverse
  - for every $\alpha \in C$ with $\alpha \neq 0$, there exists a unique $\beta \in C$ s.t. $\alpha \beta = 1$ 
- distributive property
  - $\lambda(\alpha + \beta) = \lambda\alpha + \lambda\beta$ 

*** Definition | $- \alpha$, subtraction, $\frac{1}{\alpha}$ division 

Let $- \alpha$ denote the additive inverse of $\alpha$. Thus $-\alpha$ is the unique complex number such that $\alpha + (- \alpha) = 0$. 
- Subtraction on $C$ is defined by $\beta - \alpha = \beta + (- \alpha)$

For $\alpha \neq 0$, let $\frac{1}{\alpha}$ denote the multiplicative inverse of $\alpha$. Thus $\frac{1}{\alpha}$ is the unique complex number such that $\alpha \frac{1}{\alpha} = 1$
- Division on $C$ is defined by $\frac{\beta}{\alpha} = \beta \frac{1}{\alpha}$ 

*** Definition | list, length 

Suppose $n$ is a non-negative integer. A list of length $n$ is an ordered collection of $n$ elements (which might be numbers, other lists, or more abstract entities) separated by commas and surrounded by parentheses. A list of length $n$ looks like this: $(x_1, ..., x_n)$. 

Two lists are equal iff they have the same length and the same elements in the same order. 

Many mathematicians call a list of length $n$ an $n-tuple$

*** Definition | $F^n$

$F^n$ is the set of all lists of length $n$ of the elements of $F$:

$F^n = \{(x_1, ..., x_n) : x_j \in F for j = 1, ..., n\}$

*** Definition | Addition in $F^n$

Addition in $F^n$ is the pointwise sum of the corresponding coordinates: 

$(x_1, ..., x_n) + (y_1, ..., y_n) = ((x_1 + y_1), ..., (x_n + y_n))$

*** Definition | 0 

Let 0 denote the list of length $n$ whose coordinates are all 0: $0 = (0, ..., 0)$

*** Definition | additive inverse in $F^n$

For $x \in F^n$, the additive inverse of $x$, denoted by $-x$, is the vector $-x \in F^n$ such that $x + (-x) = 0$.

In other words, if $x = (x_1, ..., x_n)$, then $-x = (-x_1, ..., -x_n)$

*** Definition | scalar multiplcation in $F^n$

The product of a number $\lambda$ and a vector in $F^n$ is computed by multiplying each coordinate of the vector by $\lambda$: 

$\lambda(x_1, ..., x_n) = (\lambda x_1, ..., \lambda x_n)$

where $\lambda \in F$ and $(x_1, ..., x_n) \in F^n$

** 1.B | Definition of a Vector Space

*** Definition | Addition, Scalar Multiplication 

- An addition on a set $V$ is a function that assigns an element $u + v \in V$ to each pair of elements $u, v \in V$
- A scalar multiplication on a set $V$ is a function that assigns an element $\lambda v \in V$ to each $\lambda \in F$ and each $v \in V$

*** Definition | Vector Space

A *vector space* is a set $V$ along with an addition on $V$ and a scalar multiplication on $V$ such that the following properties hold: 

- Commutativity
  - $u + v = v + u$ for all $u, v \in V$ 
- Associativity
  - $(u + v) + w = u + (v + w)$ 
- Additive Identity
  - There exists an element $0 \in V$ such that $v + 0 = v$ for all $v \in V$ 
- Additive Inverse
  - For every $v \in V$, there exists $w \in V$ such that $v + w = 0$ 
- Multiplicative Identity
  - $1v = v$ for all $v \in V$ 
- Distributive Properties
  - $a(u + v) = au + av$ and $(a + b)v = av + bv$

*** Definition | Vector, Point 

Elements of a vector space are called vectors or points 

*** Definition | Real Vector Space, Complex Vector Space

- A vector space over $R$ is called a real vector space
- A vector space over $C$ is called a complex vector space

*** Notation $F^S$

- If $S$ is a set, then $F^S$ denotes the set of functions from $S \to F$
- For $f, g \in F^S$, the sum $f + g \in F^S$ is the function defined by $(f + g)(x) = f(x) + g(x)$ for all $x \in S$
- For $\lambda \in F$ and $f \in F^S$, the product $\lambda F \in F^S$ is the function defined by $(\lambda f)(x) = \lambda f(x)$ for all $x \in S$

*** Theorem | Unique Additive Identity 

A vector space has a unique additive identity 

*** Theorem | Unique Additive Inverse 

Every element in a vector space has a unique additive inverse 

*** Theorem | The number 0 times a vector 

$0v = 0$ for every $v \in V$.

*** Theorem | A number times the vector 0 

$a0 = 0$ for every $a \in F$ 

*** The number $-1$ times a vector 

$(-1)v = -v$ for every $v \in V$

** 1.C | Subspaces 

*** Definition | Subspace 

A subset $U$ of $V$ is called a subspace of $V$ if $U$ is also a vector space

*** Theorem | Conditions for a subspace 
A subset $U$ of $V$ is a subspace of $V$ iff $U$ satisfies the following three conditions:

- additive identity $0 \in U$
- closed under addition $u, w \in U$ implies that $u + w \in U$
- closed under scalar multiplication $a \in F$ and $u \in F$ implies $au \in F$ 

*** Definition | Sum of Subsets 

Suppose $U_1, ..., U_m$ are subsets of $V$. The sum of $U_1, ..., U_m$, denoted $U_1 + ... + U_m$, is the set of all possible sums of elements of $U_1, ..., U_m$. 

More precisely, $U_1 + ... + U_m = \{u_1 + ... + u_m : u_1 \in U_1, ..., u_m \in U_m\}$. 

*** Theorem | Sum of Subspaces is the Smallest Containing Subspaces

Informally, the sum of subspaces is a subspace, and is in fact the smallest subspace containing all the summands 

Suppose $U_1, ..., U_m$ are subspaces of $V$. Then $U_1 + ... + U_m$ is the smallest subspace of $V$ containing $U_1, ..., U_m$. 

*** Definition | Direct Sum 

Suppose $U_1, ..., U_m$ are subspaces of $V$. 
- The sum $U_1 + ... + U_m$ is called a direct sum if each element of $U_1 + ... + U_m$ can be written in only one way as a sum of $u_1 + ... + u_m$ where each $u_j \in U_j$
- If $U_1 + ... + U_m$ is a direct sum, then $U_1 \oplus ... \oplus U_m$ denotes $U_1 + ... + U_m$, with the $\oplus$ notation serving as indication that this is a direct sum

The definition of direct sum requires that every vector in the sum have a unique representations as an appropriate sum. 

*** Theorem | Condition for a Direct Sum 

Suppose $U_1, ..., U_m$ are subspaces of $V$. Then $U_1 + ... + U_m$ is a direct sum iff the only way to write 0 as a sum $u_1 + ... + u_m$, where each $u_j \in U_j$, is by taking each $u_j$ equal to 0. 

*** Theorem | Direct Sum of Two Subspaces 

Suppose $U$ and $W$ are subspaces of $V$. Then $U + W$ is a direct sum iff $U \cap W = \{0\}$.

Sums of subspaces are analogous to unions of subsets. Similarly, direct sums of subspaces are analogous to disjoint unions of subsets. No two subspaces of a vector space can be disjoint, because both contain 0. So disjointness is replaced, at least in the case of two subspaces, with the requirement that the intersection equals $\{0\}$.


