* Vector Spaces

Linear algebra is the study of linear maps on finite dimensional vector spaces. In this chapter we will define vector spaces and discuss their elementary properties. 

Learning objectives for this chapter:
- basic properties of complex numbers
- $\mathcal{R}^n$ and $\mathcal{C}^n$
- vector spaces
- subspaces
- sums and direct sums of subspaces

** $\mathcal{R}^n$ and $\mathcal{C}^n$ 

*** Definition | Complex Numbers

- A complex number is an ordered pair $(a, b)$ where $a, b \in R$, but we will write this as $a + bi$
- The set of all complex numbers is denoted by $C = \{a + bi : a,b \in R\}$
- Addition and multiplcation on $C$
  - $(a + bi) + (c + di) = (a + c) + (b + d)i$
  - $(a + bi)(c + di) = (ac - bd) + (ad + dc)i$
  - $a, b, c, d \in R$

Properties of Complex Arithmetic 

- commutativity
  - $\alpha + \beta = \beta + \alpha$
- associtivity
  - $\alpha + (\beta + \lambda) = (\alpha + \beta) + \lambda$
- identities
  - $\lambda + 0 = \lambda$ 
- additive inverse
  - for every $\alpha \in C$, there exists a unique $\beta \in C$ s.t. $\alpha + \beta = 0$  
- multiplicative inverse
  - for every $\alpha \in C$ with $\alpha \neq 0$, there exists a unique $\beta \in C$ s.t. $\alpha \beta = 1$ 
- distributive property
  - $\lambda(\alpha + \beta) = \lambda\alpha + \lambda\beta$ 

*** Definition | $- \alpha$, subtraction, $\frac{1}{\alpha}$ division 

Let $- \alpha$ denote the additive inverse of $\alpha$. Thus $-\alpha$ is the unique complex number such that $\alpha + (- \alpha) = 0$. 
- Subtraction on $C$ is defined by $\beta - \alpha = \beta + (- \alpha)$

For $\alpha \neq 0$, let $\frac{1}{\alpha}$ denote the multiplicative inverse of $\alpha$. Thus $\frac{1}{\alpha}$ is the unique complex number such that $\alpha \frac{1}{\alpha} = 1$
- Division on $C$ is defined by $\frac{\beta}{\alpha} = \beta \frac{1}{\alpha}$ 

*** Definition | list, length 

Suppose $n$ is a non-negative integer. A list of length $n$ is an ordered collection of $n$ elements (which might be numbers, other lists, or more abstract entities) separated by commas and surrounded by parentheses. A list of length $n$ looks like this: $(x_1, ..., x_n)$. 

Two lists are equal iff they have the same length and the same elements in the same order. 

Many mathematicians call a list of length $n$ an $n-tuple$

*** Definition | $F^n$

$F^n$ is the set of all lists of length $n$ of the elements of $F$:

$F^n = \{(x_1, ..., x_n) : x_j \in F for j = 1, ..., n\}$

*** Definition | Addition in $F^n$

Addition in $F^n$ is the pointwise sum of the corresponding coordinates: 

$(x_1, ..., x_n) + (y_1, ..., y_n) = ((x_1 + y_1), ..., (x_n + y_n))$

*** Definition | 0 

Let 0 denote the list of length $n$ whose coordinates are all 0: $0 = (0, ..., 0)$

*** Definition | additive inverse in $F^n$

For $x \in F^n$, the additive inverse of $x$, denoted by $-x$, is the vector $-x \in F^n$ such that $x + (-x) = 0$.

In other words, if $x = (x_1, ..., x_n)$, then $-x = (-x_1, ..., -x_n)$

*** Definition | scalar multiplcation in $F^n$

The product of a number $\lambda$ and a vector in $F^n$ is computed by multiplying each coordinate of the vector by $\lambda$: 

$\lambda(x_1, ..., x_n) = (\lambda x_1, ..., \lambda x_n)$

where $\lambda \in F$ and $(x_1, ..., x_n) \in F^n$

